### ISSUE TITLE
Version 1.2.0 - Roadmap

### ISSUE THREAD

**Issue by SamBrishes** [RatMD/bs-lightbox#1]
- [ ] Improve Preloader script
  - [ ] Add `loader: 'all'` option to preload every image before the carousel is initialized (+ keep load / image option)
  - [ ] Fix white background effect when using the carousel with the `loader` option enabled
- [x] Add lightbox events
  - [x] `show.rat.lightbox`, triggers before lightbox is created
  - [x] `shown.rat.lightbox`, triggers after `shown.bs.modal`
  - [x] `hide.rat.lightbox`, triggers before lightbox has been hidden
  - [x] `hidden.rat.lightbox`, triggers after `hidden.bs.modal`
  - [x] `preload.rat.lightbox`, triggers before pre-loading function
  - [x] `preloaded.rat.lightbox`, triggers after all images has been pre-loaded
- [x] Filter same instances from `.invoke()` result
- [x] Add option to configure Modal, Carousel and Loader HTML snippets
- [x] Add option to configure class names for the used `<img />` or `<picture />` tag
- [ ] Add possibility to include a `<video>` element when clicking on the lightbox element
- [x] Apply `overflow:hidden` to the modal body to keep border-radius (or find another solution)
